# Color Filter

In [ ]:
import cv2
import numpy as np
import matplotlib.pyplot as plt # für RaspberryPi Code entfernen

img = cv2.imread('Bild3.png')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)

lower_red = np.array([0, 100, 110])
upper_red = np.array([345, 255, 255])

lower_blue = np.array([90, 95, 50])
upper_blue = np.array([130, 255, 255])

lower_yellow = np.array([25, 100, 100])
upper_yellow = np.array([30, 255, 255])

red_mask = cv2.inRange(hsv, lower_red, upper_red)
blue_mask = cv2.inRange(hsv, lower_blue, upper_blue)
yellow_mask = cv2.inRange(hsv, lower_yellow, upper_yellow)

final_mask = red_mask + blue_mask + yellow_mask
filter = cv2.bitwise_and(img, img, mask = final_mask)

bilateral = cv2.bilateralFilter(filter, 15,100,100) #anpassen
plt.imshow(bilateral) # für RaspberryPi Code entfernen
plt.show() # für RaspberryPi Code entfernen

result = cv2.cvtColor(filter, cv2.COLOR_BGR2RGB)
bilateral = cv2.bilateralFilter(result, 15,100,100) #anpassen
cv2.imwrite("Cubes3.png", bilateral)

# Depth Map

In [ ]:
import cv2
import torch
import matplotlib.pyplot as plt # für RaspberryPi Code entfernen
from matplotlib.colors import LinearSegmentedColormap

filename = ("Cubes2.png")

model_type = "DPT_Large"
midas = torch.hub.load("intel-isl/MiDas", model_type)

midas_transforms = torch.hub.load("intel-isl/MiDas", "transforms")
if model_type == "DPT_Large" or model_type == "DPT_Hybrid":
    transform = midas_transforms.dpt_transform

device = torch.device("cpu")
img = cv2.imread(filename)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

input_batch = transform(img).to(device)


with torch.no_grad():
    prediction = midas(input_batch)

    prediction = torch.nn.functional.interpolate(
        prediction.unsqueeze(1),
        size=img.shape[:2],
        mode="bicubic",
        align_corners=False,
    ).squeeze()
    
output = prediction.cpu().numpy()

plt.imshow(output, cmap='gray') # für RaspberryPi Code entfernen
plt.show() # für RaspberryPi Code entfernen

cv2.imwrite("DepthMap2.png", output)

# Image Segmentation

In [ ]:
import cv2
import numpy as np
import matplotlib.pyplot as plt # für RaspberryPi Code entfernen

depth_map = cv2.imread("DepthMap2.png", cv2.IMREAD_GRAYSCALE)
img = cv2.imread("Cubes2.png")

threshold_distance = 14

mask = depth_map < threshold_distance

img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

img_rgb[mask] = [0,0,0]

gray_image = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2GRAY)


threshold = 10
mask_black = cv2.threshold(gray_image, threshold, 255, cv2.THRESH_BINARY)[1]
mask_white = cv2.bitwise_not(mask_black)

img[mask_white == 255] = [255, 255, 255]
cv2.imwrite("Result2.png", img)

img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img) # für RaspberryPi Code entfernen
plt.show() # für RaspberryPi Code entfernen

# Test

In [ ]:
import cv2
import numpy as np
Test = cv2.imread("Screenshot1.png")
Test[0:720,0:545] = [255,255,255]
Test[0:720,745:1280] = [255,255,255]
Test[0:140,0:1280] = [255,255,255]
Test[320:720,0:1280] = [255,255,255]
cv2.imwrite("Test.png", Test)

In [10]:
import cv2

frame = cv2.imread("Screenshot1.png")
frame[0:720,0:545] = [255,255,255]
frame[0:720,745:1280] = [255,255,255]
frame[0:140,0:1280] = [255,255,255]
frame[320:720,0:1280] = [255,255,255]

white = [230,230,230]
black = [70,70,70]


cv2.rectangle(frame, (575, 275), (625, 325), (255, 255, 255), 3) 
roi_bottom_left = frame[275:325, 575:625]
average_color_bottom_left = np.mean(roi_bottom_left, axis=(0, 1))

cv2.rectangle(frame, (650, 275), (700, 325), (255, 255, 255), 3) 
roi_bottom_right = frame[275:325, 650:700]
average_color_bottom_right = np.mean(roi_bottom_right, axis=(0, 1))

cv2.rectangle(frame, (650, 275), (700, 325), (255, 255, 255), 3) 
roi_bottom_right = frame[275:325, 650:700]
average_color_bottom_right = np.mean(roi_bottom_right, axis=(0, 1))

cv2.rectangle(frame, (575, 100), (625, 150), (255, 255, 255), 3) 
roi_above_left = frame[100:150, 650:700]
average_color_above_left = np.mean(roi_above_left, axis=(0, 1))

cv2.rectangle(frame, (650, 100), (700, 150), (255, 255, 255), 3) 
roi_above_right = frame[100:150, 650:700]
average_color_above_right = np.mean(roi_above_right, axis=(0, 1))

for x in average_color_bottom_left:
    if x > white[0] and x > white[1] and x > white[2]:
        frame[0:210,0:655] = [255,255,255]

for x in average_color_bottom_right:
    if x > black[0] and x > black[1] and x > black[2]:
        frame[0:720,645:1280] = [255,255,255]

"""for x in average_color_above_left:
    if x > black[0] and x > black[1] and x > black[2]:
        frame[0:210,0:655] = [255,255,255]

for x in average_color_above_right:
    if x > black[0] and x > black[1] and x > black[2]:
        frame[0:210,655:1280] = [255,255,255]"""
    
cv2.imwrite("Test1.png", frame)

True

In [9]:
import cv2
Test = cv2.imread("Screenshot1.png")
PixelColor = Test[275:325, 650:700]
print(PixelColor.mean(), PixelColor)

79.95973333333333 [[[120 105 101]
  [118 103  99]
  [ 92  84  79]
  ...
  [106  63  36]
  [105  60  32]
  [104  59  31]]

 [[139 126 122]
  [138 125 121]
  [135 127 122]
  ...
  [ 44  20   8]
  [ 45  19   6]
  [ 45  19   6]]

 [[ 74  61  57]
  [ 81  68  64]
  [ 76  68  63]
  ...
  [ 68  44  32]
  [ 63  37  24]
  [ 59  33  20]]

 ...

 [[ 93  85  83]
  [ 92  84  82]
  [ 92  84  82]
  ...
  [ 95  83  82]
  [ 95  83  82]
  [ 95  83  82]]

 [[ 93  85  83]
  [ 92  84  82]
  [ 92  84  82]
  ...
  [ 95  83  82]
  [ 95  83  82]
  [ 95  83  82]]

 [[ 93  85  83]
  [ 92  84  82]
  [ 92  84  82]
  ...
  [ 95  83  82]
  [ 95  83  82]
  [ 95  83  82]]]
